class TaskMainNormalExit(Exception):
    pass


class TaskMainErrorExit(Exception):
    pass
